name: QR Code Security Scan

on:
  push:
    paths:
      - "qr_images/**"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzbar0 poppler-utils

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run QR Scanner
        run: python scripts/scan_qr.py

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: qr-scan-reports
          path: reports/
